sonar.projectKey=Csontikka_ha-cyberpower-cloud
sonar.organization=csontikka
sonar.projectName=ha-cyberpower-cloud

sonar.sources=custom_components/cyberpower_cloud
sonar.tests=tests
sonar.python.coverage.reportPaths=coverage.xml

sonar.exclusions=**/translations/**,**/__pycache__/**
sonar.test.exclusions=tests/**

sonar.python.version=3.12
